// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheckRequest - запрос для проверки состояния сервиса
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse - ответ о состоянии сервиса
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                               // "ok", "degraded", "down"
	Services      map[string]string      `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // статусы для отдельных сервисов
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetServices() map[string]string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetUserRequest - запрос для получения пользователя по ID
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetUserByTelegramIDRequest - запрос для получения пользователя по Telegram ID
type GetUserByTelegramIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTelegramIDRequest) Reset() {
	*x = GetUserByTelegramIDRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTelegramIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTelegramIDRequest) ProtoMessage() {}

func (x *GetUserByTelegramIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTelegramIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTelegramIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByTelegramIDRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

// CreateUserRequest - запрос для создания пользователя
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

// UpdateUserRequest - запрос для обновления пользователя
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

// UserResponse - ответ с данными пользователя
type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TelegramId    int64                  `protobuf:"varint,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// AddUserPreferenceRequest - запрос для добавления предпочтения
type AddUserPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagId         uint64                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserPreferenceRequest) Reset() {
	*x = AddUserPreferenceRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserPreferenceRequest) ProtoMessage() {}

func (x *AddUserPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserPreferenceRequest.ProtoReflect.Descriptor instead.
func (*AddUserPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *AddUserPreferenceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddUserPreferenceRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

// RemoveUserPreferenceRequest - запрос для удаления предпочтения
type RemoveUserPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagId         uint64                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserPreferenceRequest) Reset() {
	*x = RemoveUserPreferenceRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserPreferenceRequest) ProtoMessage() {}

func (x *RemoveUserPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserPreferenceRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveUserPreferenceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveUserPreferenceRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

// GetUserPreferencesRequest - запрос для получения предпочтений
type GetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesRequest) Reset() {
	*x = GetUserPreferencesRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesRequest) ProtoMessage() {}

func (x *GetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserPreferencesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UserPreference - модель предпочтения
type UserPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         uint64                 `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreference) Reset() {
	*x = UserPreference{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreference) ProtoMessage() {}

func (x *UserPreference) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreference.ProtoReflect.Descriptor instead.
func (*UserPreference) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserPreference) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

// UserPreferencesResponse - ответ со списком предпочтений
type UserPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   []*UserPreference      `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferencesResponse) Reset() {
	*x = UserPreferencesResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferencesResponse) ProtoMessage() {}

func (x *UserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserPreferencesResponse) GetPreferences() []*UserPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// UpdateUserLocationRequest - запрос для обновления местоположения
type UpdateUserLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserLocationRequest) Reset() {
	*x = UpdateUserLocationRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserLocationRequest) ProtoMessage() {}

func (x *UpdateUserLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserLocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserLocationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateUserLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateUserLocationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateUserLocationRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UpdateUserLocationRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// GetUserLocationRequest - запрос для получения местоположения
type GetUserLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLocationRequest) Reset() {
	*x = GetUserLocationRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLocationRequest) ProtoMessage() {}

func (x *GetUserLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLocationRequest.ProtoReflect.Descriptor instead.
func (*GetUserLocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserLocationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UserLocationResponse - ответ с местоположением
type UserLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocationResponse) Reset() {
	*x = UserLocationResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocationResponse) ProtoMessage() {}

func (x *UserLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocationResponse.ProtoReflect.Descriptor instead.
func (*UserLocationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserLocationResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UserLocationResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UserLocationResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserLocationResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UserLocationResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// FindNearbyUsersRequest - запрос для поиска пользователей рядом
type FindNearbyUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearbyUsersRequest) Reset() {
	*x = FindNearbyUsersRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearbyUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearbyUsersRequest) ProtoMessage() {}

func (x *FindNearbyUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearbyUsersRequest.ProtoReflect.Descriptor instead.
func (*FindNearbyUsersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *FindNearbyUsersRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FindNearbyUsersRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *FindNearbyUsersRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *FindNearbyUsersRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UsersResponse - ответ со списком пользователей
type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResponse        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *UsersResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

// GetUserStatsRequest - запрос для получения статистики пользователя
type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserStatsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UserStatsResponse - ответ со статистикой пользователя
type UserStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventsCreated      int32                  `protobuf:"varint,2,opt,name=events_created,json=eventsCreated,proto3" json:"events_created,omitempty"`
	EventsParticipated int32                  `protobuf:"varint,3,opt,name=events_participated,json=eventsParticipated,proto3" json:"events_participated,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt       string                 `protobuf:"bytes,5,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	IsActive           bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{18}
}

func (x *UserStatsResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserStatsResponse) GetEventsCreated() int32 {
	if x != nil {
		return x.EventsCreated
	}
	return 0
}

func (x *UserStatsResponse) GetEventsParticipated() int32 {
	if x != nil {
		return x.EventsParticipated
	}
	return 0
}

func (x *UserStatsResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserStatsResponse) GetLastActiveAt() string {
	if x != nil {
		return x.LastActiveAt
	}
	return ""
}

func (x *UserStatsResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// UpdateUserRatingRequest - запрос для обновления рейтинга пользователя
type UpdateUserRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RatingChange  float32                `protobuf:"fixed32,2,opt,name=rating_change,json=ratingChange,proto3" json:"rating_change,omitempty"` // Изменение рейтинга (положительное или отрицательное)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRatingRequest) Reset() {
	*x = UpdateUserRatingRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRatingRequest) ProtoMessage() {}

func (x *UpdateUserRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRatingRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRatingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateUserRatingRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRatingRequest) GetRatingChange() float32 {
	if x != nil {
		return x.RatingChange
	}
	return 0
}

// UpdateNotificationSettingsRequest - запрос для обновления настроек уведомлений
type UpdateNotificationSettingsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewEventNotification bool                   `protobuf:"varint,2,opt,name=new_event_notification,json=newEventNotification,proto3" json:"new_event_notification,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsRequest) Reset() {
	*x = UpdateNotificationSettingsRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsRequest) ProtoMessage() {}

func (x *UpdateNotificationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateNotificationSettingsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateNotificationSettingsRequest) GetNewEventNotification() bool {
	if x != nil {
		return x.NewEventNotification
	}
	return false
}

// GetNotificationSettingsRequest - запрос для получения настроек уведомлений
type GetNotificationSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationSettingsRequest) Reset() {
	*x = GetNotificationSettingsRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationSettingsRequest) ProtoMessage() {}

func (x *GetNotificationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetNotificationSettingsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// NotificationSettingsResponse - ответ с настройками уведомлений
type NotificationSettingsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NewEventNotification bool                   `protobuf:"varint,1,opt,name=new_event_notification,json=newEventNotification,proto3" json:"new_event_notification,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NotificationSettingsResponse) Reset() {
	*x = NotificationSettingsResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSettingsResponse) ProtoMessage() {}

func (x *NotificationSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSettingsResponse.ProtoReflect.Descriptor instead.
func (*NotificationSettingsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{22}
}

func (x *NotificationSettingsResponse) GetNewEventNotification() bool {
	if x != nil {
		return x.NewEventNotification
	}
	return false
}

// SimpleResponse - простой ответ об успешности операции
type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{23}
}

func (x *SimpleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimpleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_user_user_proto protoreflect.FileDescriptor

const file_pkg_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/user/user.proto\x12\x04user\"\x14\n" +
	"\x12HealthCheckRequest\"\xcd\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12C\n" +
	"\bservices\x18\x02 \x03(\v2'.user.HealthCheckResponse.ServicesEntryR\bservices\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a;\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"=\n" +
	"\x1aGetUserByTelegramIDRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\"b\n" +
	"\x11CreateUserRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\"Q\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\"\x85\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\x03R\n" +
	"telegramId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\"J\n" +
	"\x18AddUserPreferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x04R\x05tagId\"M\n" +
	"\x1bRemoveUserPreferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x04R\x05tagId\"4\n" +
	"\x19GetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"'\n" +
	"\x0eUserPreference\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x04R\x05tagId\"Q\n" +
	"\x17UserPreferencesResponse\x126\n" +
	"\vpreferences\x18\x01 \x03(\v2\x14.user.UserPreferenceR\vpreferences\"\xb4\x01\n" +
	"\x19UpdateUserLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\"1\n" +
	"\x16GetUserLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x96\x01\n" +
	"\x14UserLocationResponse\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"\x85\x01\n" +
	"\x16FindNearbyUsersRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limit\"9\n" +
	"\rUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.user.UserResponseR\x05users\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xe6\x01\n" +
	"\x11UserStatsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12%\n" +
	"\x0eevents_created\x18\x02 \x01(\x05R\reventsCreated\x12/\n" +
	"\x13events_participated\x18\x03 \x01(\x05R\x12eventsParticipated\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12$\n" +
	"\x0elast_active_at\x18\x05 \x01(\tR\flastActiveAt\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"W\n" +
	"\x17UpdateUserRatingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12#\n" +
	"\rrating_change\x18\x02 \x01(\x02R\fratingChange\"r\n" +
	"!UpdateNotificationSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x124\n" +
	"\x16new_event_notification\x18\x02 \x01(\bR\x14newEventNotification\"9\n" +
	"\x1eGetNotificationSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"T\n" +
	"\x1cNotificationSettingsResponse\x124\n" +
	"\x16new_event_notification\x18\x01 \x01(\bR\x14newEventNotification\"D\n" +
	"\x0eSimpleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf2\b\n" +
	"\x15JollyRogerUserService\x12B\n" +
	"\vHealthCheck\x12\x18.user.HealthCheckRequest\x1a\x19.user.HealthCheckResponse\x123\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\x12K\n" +
	"\x13GetUserByTelegramID\x12 .user.GetUserByTelegramIDRequest\x1a\x12.user.UserResponse\x129\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x129\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12I\n" +
	"\x11AddUserPreference\x12\x1e.user.AddUserPreferenceRequest\x1a\x14.user.SimpleResponse\x12O\n" +
	"\x14RemoveUserPreference\x12!.user.RemoveUserPreferenceRequest\x1a\x14.user.SimpleResponse\x12T\n" +
	"\x12GetUserPreferences\x12\x1f.user.GetUserPreferencesRequest\x1a\x1d.user.UserPreferencesResponse\x12K\n" +
	"\x12UpdateUserLocation\x12\x1f.user.UpdateUserLocationRequest\x1a\x14.user.SimpleResponse\x12K\n" +
	"\x0fGetUserLocation\x12\x1c.user.GetUserLocationRequest\x1a\x1a.user.UserLocationResponse\x12D\n" +
	"\x0fFindNearbyUsers\x12\x1c.user.FindNearbyUsersRequest\x1a\x13.user.UsersResponse\x12B\n" +
	"\fGetUserStats\x12\x19.user.GetUserStatsRequest\x1a\x17.user.UserStatsResponse\x12E\n" +
	"\x10UpdateUserRating\x12\x1d.user.UpdateUserRatingRequest\x1a\x12.user.UserResponse\x12[\n" +
	"\x1aUpdateNotificationSettings\x12'.user.UpdateNotificationSettingsRequest\x1a\x14.user.SimpleResponse\x12c\n" +
	"\x17GetNotificationSettings\x12$.user.GetNotificationSettingsRequest\x1a\".user.NotificationSettingsResponseB&Z$JollyRogerUserService/pkg/proto/userb\x06proto3"

var (
	file_pkg_proto_user_user_proto_rawDescOnce sync.Once
	file_pkg_proto_user_user_proto_rawDescData []byte
)

func file_pkg_proto_user_user_proto_rawDescGZIP() []byte {
	file_pkg_proto_user_user_proto_rawDescOnce.Do(func() {
		file_pkg_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_user_user_proto_rawDesc), len(file_pkg_proto_user_user_proto_rawDesc)))
	})
	return file_pkg_proto_user_user_proto_rawDescData
}

var file_pkg_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pkg_proto_user_user_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),                // 0: user.HealthCheckRequest
	(*HealthCheckResponse)(nil),               // 1: user.HealthCheckResponse
	(*GetUserRequest)(nil),                    // 2: user.GetUserRequest
	(*GetUserByTelegramIDRequest)(nil),        // 3: user.GetUserByTelegramIDRequest
	(*CreateUserRequest)(nil),                 // 4: user.CreateUserRequest
	(*UpdateUserRequest)(nil),                 // 5: user.UpdateUserRequest
	(*UserResponse)(nil),                      // 6: user.UserResponse
	(*AddUserPreferenceRequest)(nil),          // 7: user.AddUserPreferenceRequest
	(*RemoveUserPreferenceRequest)(nil),       // 8: user.RemoveUserPreferenceRequest
	(*GetUserPreferencesRequest)(nil),         // 9: user.GetUserPreferencesRequest
	(*UserPreference)(nil),                    // 10: user.UserPreference
	(*UserPreferencesResponse)(nil),           // 11: user.UserPreferencesResponse
	(*UpdateUserLocationRequest)(nil),         // 12: user.UpdateUserLocationRequest
	(*GetUserLocationRequest)(nil),            // 13: user.GetUserLocationRequest
	(*UserLocationResponse)(nil),              // 14: user.UserLocationResponse
	(*FindNearbyUsersRequest)(nil),            // 15: user.FindNearbyUsersRequest
	(*UsersResponse)(nil),                     // 16: user.UsersResponse
	(*GetUserStatsRequest)(nil),               // 17: user.GetUserStatsRequest
	(*UserStatsResponse)(nil),                 // 18: user.UserStatsResponse
	(*UpdateUserRatingRequest)(nil),           // 19: user.UpdateUserRatingRequest
	(*UpdateNotificationSettingsRequest)(nil), // 20: user.UpdateNotificationSettingsRequest
	(*GetNotificationSettingsRequest)(nil),    // 21: user.GetNotificationSettingsRequest
	(*NotificationSettingsResponse)(nil),      // 22: user.NotificationSettingsResponse
	(*SimpleResponse)(nil),                    // 23: user.SimpleResponse
	nil,                                       // 24: user.HealthCheckResponse.ServicesEntry
}
var file_pkg_proto_user_user_proto_depIdxs = []int32{
	24, // 0: user.HealthCheckResponse.services:type_name -> user.HealthCheckResponse.ServicesEntry
	10, // 1: user.UserPreferencesResponse.preferences:type_name -> user.UserPreference
	6,  // 2: user.UsersResponse.users:type_name -> user.UserResponse
	0,  // 3: user.JollyRogerUserService.HealthCheck:input_type -> user.HealthCheckRequest
	2,  // 4: user.JollyRogerUserService.GetUser:input_type -> user.GetUserRequest
	3,  // 5: user.JollyRogerUserService.GetUserByTelegramID:input_type -> user.GetUserByTelegramIDRequest
	4,  // 6: user.JollyRogerUserService.CreateUser:input_type -> user.CreateUserRequest
	5,  // 7: user.JollyRogerUserService.UpdateUser:input_type -> user.UpdateUserRequest
	7,  // 8: user.JollyRogerUserService.AddUserPreference:input_type -> user.AddUserPreferenceRequest
	8,  // 9: user.JollyRogerUserService.RemoveUserPreference:input_type -> user.RemoveUserPreferenceRequest
	9,  // 10: user.JollyRogerUserService.GetUserPreferences:input_type -> user.GetUserPreferencesRequest
	12, // 11: user.JollyRogerUserService.UpdateUserLocation:input_type -> user.UpdateUserLocationRequest
	13, // 12: user.JollyRogerUserService.GetUserLocation:input_type -> user.GetUserLocationRequest
	15, // 13: user.JollyRogerUserService.FindNearbyUsers:input_type -> user.FindNearbyUsersRequest
	17, // 14: user.JollyRogerUserService.GetUserStats:input_type -> user.GetUserStatsRequest
	19, // 15: user.JollyRogerUserService.UpdateUserRating:input_type -> user.UpdateUserRatingRequest
	20, // 16: user.JollyRogerUserService.UpdateNotificationSettings:input_type -> user.UpdateNotificationSettingsRequest
	21, // 17: user.JollyRogerUserService.GetNotificationSettings:input_type -> user.GetNotificationSettingsRequest
	1,  // 18: user.JollyRogerUserService.HealthCheck:output_type -> user.HealthCheckResponse
	6,  // 19: user.JollyRogerUserService.GetUser:output_type -> user.UserResponse
	6,  // 20: user.JollyRogerUserService.GetUserByTelegramID:output_type -> user.UserResponse
	6,  // 21: user.JollyRogerUserService.CreateUser:output_type -> user.UserResponse
	6,  // 22: user.JollyRogerUserService.UpdateUser:output_type -> user.UserResponse
	23, // 23: user.JollyRogerUserService.AddUserPreference:output_type -> user.SimpleResponse
	23, // 24: user.JollyRogerUserService.RemoveUserPreference:output_type -> user.SimpleResponse
	11, // 25: user.JollyRogerUserService.GetUserPreferences:output_type -> user.UserPreferencesResponse
	23, // 26: user.JollyRogerUserService.UpdateUserLocation:output_type -> user.SimpleResponse
	14, // 27: user.JollyRogerUserService.GetUserLocation:output_type -> user.UserLocationResponse
	16, // 28: user.JollyRogerUserService.FindNearbyUsers:output_type -> user.UsersResponse
	18, // 29: user.JollyRogerUserService.GetUserStats:output_type -> user.UserStatsResponse
	6,  // 30: user.JollyRogerUserService.UpdateUserRating:output_type -> user.UserResponse
	23, // 31: user.JollyRogerUserService.UpdateNotificationSettings:output_type -> user.SimpleResponse
	22, // 32: user.JollyRogerUserService.GetNotificationSettings:output_type -> user.NotificationSettingsResponse
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_user_user_proto_init() }
func file_pkg_proto_user_user_proto_init() {
	if File_pkg_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_user_user_proto_rawDesc), len(file_pkg_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_user_user_proto_goTypes,
		DependencyIndexes: file_pkg_proto_user_user_proto_depIdxs,
		MessageInfos:      file_pkg_proto_user_user_proto_msgTypes,
	}.Build()
	File_pkg_proto_user_user_proto = out.File
	file_pkg_proto_user_user_proto_goTypes = nil
	file_pkg_proto_user_user_proto_depIdxs = nil
}
