postgres:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  dbname: "teamfinder"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

grpc:
  port: 50051
